# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
spec:
  replicas: 3 # Number of pods
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
        - name: your-app
          image: your-dockerhub-username/your-app-image:latest
          ports:
            - containerPort: 8080 # Your app's port
          resources: # Resource limits (optional)
            limits:
              cpu: "500m"
              memory: "512Mi"
